### ISSUE TITLE
No contact

### ISSUE THREAD

**Issue by vito-gmi** [n-elia/Arduino-Nano-33-IoT-Azure-DPS-with-SSL-X.509-auth#1]
Dear Nicola,

Sorry for opening this issue, but I could not find how I can contact you, e.g., an email address. Will you be able to give me and contact and help me with some issues related to the connection with Azure IoT Hub and my Arduino MKR 1010 WiFi ( quite similart to the Nano 33 IoT) ?

You can directly contact me on vitomirpavlov@gmail.com, if you do not want to share yours.

Thanks in advance!

BR,
Vitomir

**Comment by n-elia** [comment]
Hi Vitomir, 
Since we got in contact privately, I'm going to close this issue!
Bye,
Nicola
